/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bileco_agma.view;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Balo Family
 */
public class Congratulations extends javax.swing.JDialog {

    public Congratulations(java.awt.Frame parent, boolean modal, String winnerName) {
        super(parent, modal);
        BufferedImage myImage;
        try {
            myImage = ImageIO.read( getClass().getResource("/bileco_agma/images/rays-bg.png") );
            setContentPane( new ImagePanel(myImage) );
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        
        String[] tokens = winnerName.toUpperCase().split(" ");
        
        final int MAX_LABEL_CHARS = 18;
        if (winnerName.length() <= MAX_LABEL_CHARS) {
            lbl_winnerName1.setText(winnerName);
            lbl_winnerName2.setText("");
        }
        else {
            int lastIndexOfSpace = winnerName.lastIndexOf(" ", MAX_LABEL_CHARS);
            lbl_winnerName1.setText(winnerName.substring(0, lastIndexOfSpace));
            lbl_winnerName2.setText(winnerName.substring(lastIndexOfSpace + 1));
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel2D label1_2d = new JLabel2D();
        label1_2d.setOutlineColor(new Color(210, 78, 4));          
        label1_2d.setStroke(new BasicStroke(4f));

        JLabel2D label3_2d = new JLabel2D();
        label3_2d.setOutlineColor(new Color(210, 78, 4));          
        label3_2d.setStroke(new BasicStroke(4f));

        jLabel1 = label1_2d;
        jLabel3 = label3_2d;
        lbl_winnerName1 = new javax.swing.JLabel();
        lbl_winnerName2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(800, 435));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 197, 32));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Congratulations!");

        jLabel3.setFont(new java.awt.Font("Impact", 0, 62)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 197, 32));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("YOU WON!");

        lbl_winnerName1.setFont(new java.awt.Font("Vijaya", 1, 85)); // NOI18N
        lbl_winnerName1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_winnerName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_winnerName1.setText("STEPHEN JANSEEN");

        lbl_winnerName2.setFont(new java.awt.Font("Vijaya", 1, 85)); // NOI18N
        lbl_winnerName2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_winnerName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_winnerName2.setText("DELA PENA BALO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_winnerName1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addComponent(lbl_winnerName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_winnerName1)
                .addGap(4, 4, 4)
                .addComponent(lbl_winnerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(69, 69, 69))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("WIndows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Congratulations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Congratulations dialog = new Congratulations(
                        new javax.swing.JFrame(), true, "STEPHEN JANSEEN DELA PENA BALO");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_winnerName1;
    private javax.swing.JLabel lbl_winnerName2;
    // End of variables declaration//GEN-END:variables
}
