/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bileco_agma.view;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * 
 *
 * @author Balo Family
 */
public class MainScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        BufferedImage myImage;
        try {
            myImage = ImageIO.read( getClass().getResource("/bileco_agma/images/christmas_bg.png") );
            setContentPane( new ImagePanel(myImage) );
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        
        setIconImage(
                Toolkit.getDefaultToolkit().getImage(
                        getClass().getResource("/bileco_agma/images/BILECO LOGO icon.png")));
        
        /*final int currYear = Calendar.getInstance().get(Calendar.YEAR);
        final int BILECO_ANNUAL_AGMA = currYear - 1987;
        int lastDigit = BILECO_ANNUAL_AGMA % 10;
        String suffix = (lastDigit == 1 && BILECO_ANNUAL_AGMA != 11)? "st" : 
                (lastDigit == 2 && BILECO_ANNUAL_AGMA != 12)? "nd" : 
                (lastDigit == 3 && BILECO_ANNUAL_AGMA != 13)? "rd" : "th";
        lbl_AGMA.setText(BILECO_ANNUAL_AGMA + suffix + " ANNUAL GENERAL MEMBERSHIP ASSEMBLY");*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        JLabel2D label3 = new JLabel2D();
        jLabel3 = label3;
        JLabelDropShadow label1 = new JLabelDropShadow(null, 0);
        jLabel1 = label1;
        JLabel2D lblAGMA = new JLabel2D();
        lbl_AGMA = lblAGMA;
        btnDrawRaffle = new javax.swing.JButton();
        panelTicket = new javax.swing.JPanel();
        digit1 = new javax.swing.JLabel();
        digit2 = new javax.swing.JLabel();
        digit3 = new javax.swing.JLabel();
        digit4 = new javax.swing.JLabel();
        digit5 = new javax.swing.JLabel();
        ticket_bg = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        btn_settings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Raffle Draw");
        setMinimumSize(new java.awt.Dimension(1139, 675));
        setResizable(false);

        header.setOpaque(false);

        jLabel3.setBackground(new java.awt.Color(39, 242, 59));
        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 75, 150));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("E-RAFFLE DRAW");
        label3.setOutlineColor(Color.white); 
        label3.setStroke(new BasicStroke(4f));

        jLabel1.setBackground(new java.awt.Color(39, 242, 59));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("BILECO YEAR-END PARTY &");
        label1.setLeftShadow(-3, -3, Color.WHITE);    // drop shadow w/ highlight   
        label1.setRightShadow(2, 3, Color.WHITE);

        lbl_AGMA.setBackground(new java.awt.Color(39, 242, 59));
        lbl_AGMA.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        lbl_AGMA.setForeground(new java.awt.Color(0, 204, 51));
        lbl_AGMA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_AGMA.setText("FAMILY DAY 2015");
        lblAGMA.setOutlineColor(Color.white); 
        lblAGMA.setStroke(new BasicStroke(4f));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_AGMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_AGMA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnDrawRaffle.setBackground(new java.awt.Color(25, 71, 150));
        btnDrawRaffle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDrawRaffle.setForeground(new java.awt.Color(255, 255, 255));
        btnDrawRaffle.setText("DRAW RAFFLE TICKET");
        btnDrawRaffle.setActionCommand("");
        btnDrawRaffle.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(120, 120, 120)));
        btnDrawRaffle.setFocusPainted(false);

        panelTicket.setOpaque(false);
        panelTicket.setPreferredSize(new java.awt.Dimension(510, 170));
        panelTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        digit1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        digit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digit1.setPreferredSize(new java.awt.Dimension(28, 60));
        panelTicket.add(digit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, 140));

        digit2.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        digit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digit2.setText("0");
        panelTicket.add(digit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 90, 140));

        digit3.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        digit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digit3.setText("0");
        panelTicket.add(digit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 80, 140));

        digit4.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        digit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digit4.setText("0");
        digit4.setPreferredSize(new java.awt.Dimension(28, 60));
        panelTicket.add(digit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 90, 140));

        digit5.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        digit5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digit5.setText("0");
        panelTicket.add(digit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 90, 140));

        ticket_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bileco_agma/images/raffleticket.png"))); // NOI18N
        panelTicket.add(ticket_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 360));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bileco_agma/images/BILECO LOGO.png"))); // NOI18N
        logo1.setPreferredSize(null);

        btn_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bileco_agma/images/ic_action_settings.png"))); // NOI18N
        btn_settings.setToolTipText("Settings");
        btn_settings.setBorder(null);
        btn_settings.setBorderPainted(false);
        btn_settings.setOpaque(false);
        btn_settings.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bileco_agma/images/ic_action_settings.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDrawRaffle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_settings)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(panelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDrawRaffle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDrawRaffle;
    private javax.swing.JButton btn_settings;
    private javax.swing.JLabel digit1;
    private javax.swing.JLabel digit2;
    private javax.swing.JLabel digit3;
    private javax.swing.JLabel digit4;
    private javax.swing.JLabel digit5;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_AGMA;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel panelTicket;
    private javax.swing.JLabel ticket_bg;
    // End of variables declaration//GEN-END:variables
    
    
    public JButton getDrawRaffleTicketBtn() {
        return btnDrawRaffle;
    }

    public JButton getSettingsBtn() {
        return btn_settings;
    }
    
    public JLabel getTenThounsandsDigit() {
        return digit1;
    }

    public void setTenThousandsDigit(String string) {
        digit1.setText(string);
    }
    
    public JLabel getThousandsDigit() {
        return digit2;
    }

    public void setThousandsDigit(String string) {
        digit2.setText(string);
    }
    
    public JLabel getHundredsDigit() {
        return digit3;
    }

    public void setHundredsDigit(String string) {
        digit3.setText(string);
    }
    
    public JLabel getTensDigit() {
        return digit4;
    }

    public void setTensDigit(String string) {
        digit4.setText(string);
    }
    
    public JLabel getOnesDigitLbl() {
        return digit5;
    }
    
    public void setOnesDigit(String string) {
        digit5.setText(string);
    }
    
    public void highlightTenThousandsDigit() {
        digit1.setForeground(Color.red);
    }

    public void highlightThousandsDigit() {
        digit2.setForeground(Color.red);
    }

    public void highlightHundredsDigit() {
        digit3.setForeground(Color.red);
    }

    public void highlightTensDigit() {
        digit4.setForeground(Color.red);
    }

    public void highlightOnesDigit() {
        digit5.setForeground(Color.red);
    }
    
    public void unhighlightDigits() {
        digit1.setForeground(Color.BLACK);
        digit2.setForeground(Color.BLACK);
        digit3.setForeground(Color.BLACK);
        digit4.setForeground(Color.BLACK);
        digit5.setForeground(Color.BLACK);
    }
}
